version: "3"
services:
  install:
    image: node:18.15
    user: node
    volumes:
      - .:/app
    command: bash -c "cd /app && rm -rf node_modules && rm -f package-lock.json && npm i"
  installTest:
    image: node:18.15
    user: node
    volumes:
      - .:/app
    command: bash -c "cd /app/test && rm -rf node_modules && rm -f package-lock.json && npm i"
  build: 
    image: node:18.15
    user: root
    volumes:
      - .:/app
    command: bash -c "cd /app && npm run build"
  test:
    image: node:18.15
    user: root
    ports:
      - "8070:8080"
    volumes:
      - .:/app
    command: bash -c "cd /app && npm run test"
